zookeeper:
  image: 'bitnami/zookeeper:latest'
  net: host
  environment:
    ALLOW_ANONYMOUS_LOGIN: "yes"
kafka:
  image: 'bitnami/kafka:latest'
  net: host
  environment:
    ALLOW_PLAINTEXT_LISTENER: "yes"
    KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
db:
  image: postgres
  net: host 
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: teste
payments:
  build: ./payments
  net: host
mail_sender:
  build: ./mail-sender
  net: host
  environment:
    MAIL_PASSWORD: $MAIL_PASSWORD
logstash:
  image: docker.elastic.co/logstash/logstash:7.12.0
  net: host
  environment:
    MAIL_PASSWORD: $MAIL_PASSWORD
  volumes:
    - /home/icaropz/payments/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
