apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
  - port: 9600
  selector:
    app: logstash
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 2
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.12.0
        name: logstash
        env:
        - name: MAIL_PASSWORD
          value: $MAIL_PASSWORD
        ports:
        - containerPort: 9600
          name: logstash
        volumeMounts:
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-pipelines
        hostPath:
          path: /home/icaropz/payments/logstash/
