apiVersion: v1
kind: Service
metadata:
  name: mail-sender
spec:
  ports:
  - port: 8080
  selector:
    app: mail-sender
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-sender
spec:
  selector:
    matchLabels:
      app: mail-sender
  replicas: 2
  template:
    metadata:
      labels:
        app: mail-sender
    spec:
      containers:
      - image: mail-sender
        name: mail-sender
        imagePullPolicy: Never
        env:
        - name: MAIL_PASSWORD
          value: $MAIL_PASSWORD
        ports:
        - containerPort: 8080
          name: mail-sender
