apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  ports:
  - port: 30001
    nodePort: 30800
  selector:
    app: payments
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  replicas: 2
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: payments
        name: payments
        imagePullPolicy: Never
        ports:
        - containerPort: 30001
          name: payments
